#!/usr/bin/python3
import math
import sys


def factorize_file(file_path):
    with open(file_path, "r") as file:
        for line in file:
            number = int(line.strip())
            factors = factorize(number)
            factorization = "{}={}".format(number, "*".join(map(str, factors)))
            print(factorization)


def factorize(number):
    factors = []
    for i in range(2, int(math.isqrt(number)) + 1):
        if number % i == 0:
            factors.append(i)
            factors.append(number // i)
            break  # Stop after finding two factors
    return factors


if __name__ == "__main__":
    factorize_file(sys.argv[1])
